export default {
  COINS_LOAD: 'COINS_LOAD',
  COINS_LOAD_SUCCESS: 'COINS_LOAD_SUCCESS',
  COINS_LOAD_ERROR: 'COINS_LOAD_ERROR',
  NOTIFICATION_LOAD: 'NOTIFICATION_LOAD',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',

  ACCOUNT_LOAD: 'ACCOUNT_LOAD',
  ACCOUNT_LOAD_SUCCESS: 'ACCOUNT_LOAD_SUCCESS',
  ACCOUNT_LOAD_ERROR: 'ACCOUNT_LOAD_ERROR'
};
